version: '3.8'
networks:
  mynet:
    driver: bridge
services:
  database-service:
    container_name: database-container
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - mynet
    restart: always
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=MYSQL
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_ADDR=database-service
      - DB_PORT=3306
      - DB_DATABASE=microservice
    ports:
        - 8888:8080
    networks:
        - mynet
    depends_on:
        - database-service
  authenservice:
    build: ./authenticationservice
    volumes:
      - ./authenticationservice:/authenticationservice
      - ~/.m2:/root/.m2
    working_dir: /authenticationservice
    ports:
      - 8188:8080
    command: mvn clean spring-boot:run
    networks:
      - mynet
  orderservice:
    build: ./orderservice
    volumes:
      - ./orderservice:/orderservice
      - ~/.m2:/root/.m2
    working_dir: /orderservice
    ports:
      - 8000:8000
    command: mvn clean spring-boot:run
    networks:
      - mynet
#    depends_on:
#      - database-service


  paymentservice:
    build: ./paymentservice
    volumes:
      - ./paymentservice:/paymentservice
      - ~/.m2:/root/.m2
    working_dir: /paymentservice
    ports:
      - 8081:8080
    command: mvn clean spring-boot:run
#  keycloak:
#    image: quay.io/keycloak/keycloak:legacy
#    environment:
#      DB_VENDOR: MYSQL
#      DB_ADDR: database-service
#      DB_DATABASE: microservice
#      DB_USER: root
#      DB_PASSWORD: root
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: Pa55w0rd
#    ports:
#      - 8888:8080
#    depends_on:
#      - database-service


